### ISSUE TITLE
\NowCerts\HttpClient::setOAuth

### ISSUE THREAD

**Issue by djomla1989** [NowCerts/NowCerts-PHP-SDK#1]
Hi,

Maybe you can add setter for oAuth, because we can't use tokens outside \NowCerts\HttpClient::authenticate

With this, we can reuse token until expires_in

  ```
public static function setOAuth(OAuth $oAuth) {
    self::$oauth = $oAuth;
  }
```

**Comment by jacobembree** [comment]
Thanks, @djomla1989.
