### ISSUE TITLE
If $value == null it return current date

### ISSUE THREAD

**Issue by djomla1989** [NowCerts/NowCerts-PHP-SDK#2]
https://github.com/NowCerts/NowCerts-PHP-SDK/blob/eb857f6d5ae081b166144870f872660e242a560a/src/Policy.php#L255

If there is no values for dates params, it will return current date. I guess this is wrong as it should stay `null`?

**Comment by jacobembree** [comment]
I could go either way on this one.  You would expect a policy to have a creation date, and "now" is a sensible default, but I'm not positive it's optimal to have a default in this case.  I'll have to think about it some more or see if anyone else wants to chime in.

**Comment by NowCerts** [comment]
To be honest I am a little lost. I am not a programmer, but a person on the
business side.
A policy in Nowcerts always has an Effective date. It is a required field.
And it should aways have a Create date (a system generated value). So No
reason not to be able to pass either of those.
But if for whatever reason that is no possible, it is better to pass NULL
that a date that is not the actual date ( l effective  or creation date)

These for sure need ot be NULL. It is not common that these are present

case 'cancellationDate':
case 'reinstatementDate'

Regards,
- Peter



*Aut viam inveniam aut faciam*1338 S Foothill Dr. 222
Salt Lake City, UT 84108
Toll Free: (888) 586-4792 x 103
Fax: (888) 687-8450
http://www.nowcerts.com/
Answers to many commonly asked questions can be found on our support site - go
to support site <https://nowcerts.freshdesk.com/support/home>

**Comment by jacobembree** [comment]
Thanks for your input, @djomla1989 and Peter (@NowCerts).  That makes sense.  I removed the default and set the date as-is in all cases for all date fields except where a string is provided which only then is converted to a `DateTime` object.

**Comment by djomla1989** [comment]
Awesome! Than you!

**Comment by NowCerts** [comment]
Thank you both!
